import Link from "next/link";
import { notFound } from "next/navigation";
import { NoxaLogo } from "@/components/brand/NoxaLogo";
import { FollowSubscriptionForm } from "@/components/meets/FollowSubscriptionForm";
import { loadOrganizerBySlug, loadOrganizerCommunity, loadOrganizerEvents, type OrganizerEvent } from "./organizer-data";
import styles from "./OrganizerPublic.module.css";

function formatDate(event: OrganizerEvent, locale: "en" | "el") { return new Intl.DateTimeFormat(locale === "el" ? "el-GR" : "en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: false, timeZone: event.timezone || "Europe/Athens" }).format(new Date(event.starts_at)); }
export async function OrganizerProfile({ slug, locale }: { slug: string; locale: "en" | "el" }) {
  const organizer = await loadOrganizerBySlug(slug); if (!organizer) notFound();
  const [{ upcoming, past }, community] = await Promise.all([loadOrganizerEvents(organizer.id), loadOrganizerCommunity(organizer.community_id)]);
  const base = locale === "el" ? "/el" : "";
  const t = locale === "el" ? { eyebrow: "NOXA ORGANIZER", verified: "VERIFIED", type: "Τύπος", links: "Links", community: "Community", upcoming: "Επόμενα events", past: "Past events", noUpcoming: "Δεν υπάρχουν upcoming public events.", noPast: "Δεν υπάρχουν past public events.", follow: `Ακολούθησε ${organizer.name} για NOXA updates` } : { eyebrow: "NOXA ORGANIZER", verified: "VERIFIED", type: "Type", links: "Links", community: "Community", upcoming: "Upcoming events", past: "Past events", noUpcoming: "No upcoming public events.", noPast: "No past public events.", follow: `Follow ${organizer.name} for NOXA updates` };
  const renderEvents = (events: OrganizerEvent[], empty: string) => events.length ? <div className={styles.eventList}>{events.map((event) => <Link className={styles.eventCard} href={`${base}/meets/${event.public_slug}`} key={event.id}><span className={styles.eventDate}>{formatDate(event, locale)}</span><div><h3>{event.title}</h3><p>{event.city ?? event.location_text ?? event.region ?? organizer.country_code}</p></div><span>→</span></Link>)}</div> : <div className={styles.empty}>{empty}</div>;
  return <div className={styles.page}><header className={styles.header}><Link className={styles.brand} href={base || "/"} aria-label="NOXA home"><NoxaLogo /></Link><Link className={styles.back} href={`${base}/organizers`}>← Organizers</Link></header><main><section className={styles.hero}><div className={styles.shell}><p className={styles.eyebrow}>{t.eyebrow}</p><h1>{organizer.name}</h1><div className={styles.profileMeta}>{organizer.verified ? <span>{t.verified}</span> : null}{organizer.partner ? <span>{organizer.partner_label || "NOXA PARTNER"}</span> : null}<span>{organizer.organizer_type}</span><span>{[organizer.city, organizer.country_code].filter(Boolean).join(" · ")}</span></div></div></section><div className={`${styles.shell} ${styles.profileGrid}`}><div><section className={styles.section}><div className={styles.sectionTitle}><div><span>NOXA MEETS</span><h2>{t.upcoming}</h2></div></div>{renderEvents(upcoming, t.noUpcoming)}</section><section className={`${styles.section} ${styles.past}`}><div className={styles.sectionTitle}><div><span>ARCHIVE</span><h2>{t.past}</h2></div></div>{renderEvents(past, t.noPast)}</section></div><aside className={styles.side}><FollowSubscriptionForm compact locale={locale} target={{ type: "organizer", organizerId: organizer.id }} title={t.follow} /><div className={styles.panel}><span>{t.links}</span>{organizer.instagram_url ? <a href={organizer.instagram_url} target="_blank" rel="noreferrer">Instagram ↗</a> : null}{organizer.website_url ? <a href={organizer.website_url} target="_blank" rel="noreferrer">Website ↗</a> : null}</div>{community ? <div className={styles.panel}><span>{t.community}</span><Link href={`${base}/communities/${community.slug}`}>{community.name} →</Link>{community.verified ? <p>VERIFIED COMMUNITY</p> : null}</div> : null}<div className={styles.panel}><span>{t.type}</span><p>{organizer.organizer_type}</p></div></aside></div></main></div>;
}
