import Link from "next/link";
import type { Locale } from "@/i18n/landing-copy";
import { matchesDateFilter } from "@/lib/meets/dateFilters";
import { isEventCurrentlyVisible } from "@/lib/meets/eventVisibility";
import styles from "./RadarHomeSpotlight.module.css";
const SUPABASE_URL="https://qrouwtqsqrfeeeppyeru.supabase.co";const SUPABASE_PUBLISHABLE_KEY="sb_publishable_vR9wivNa_fIb0QKmqua6Wg_H_7OPvUk";
const CATEGORY:Record<string,string>={car_meet:"CAR MEET",moto_meet:"MOTO MEET",track_day:"TRACK DAY",drag:"DRAG",drift:"DRIFT",rally:"RALLY",show:"AUTO SHOW",cars_and_coffee:"CARS & COFFEE",group_drive:"GROUP DRIVE",festival:"FESTIVAL",other:"EVENT"};
type Row={id:string;public_slug:string;title:string;event_type:string;starts_at:string;ends_at:string|null;timezone:string|null;city:string|null;location_text:string|null;country_code:string};
const copy={en:{eyebrow:"THIS WEEKEND IN GREECE",title:"Where are you going?",body:"See this weekend’s automotive events across Greece.",cta:"Explore this weekend",empty:"No public events are listed for this weekend yet.",events:"events",cities:"cities",next:"Upcoming after this weekend",view:"View event"},el:{eyebrow:"ΑΥΤΟ ΤΟ WEEKEND ΣΤΗΝ ΕΛΛΑΔΑ",title:"Πού θα πας;",body:"Δες τα automotive events αυτού του weekend σε όλη την Ελλάδα.",cta:"Δες αυτό το weekend",empty:"Δεν υπάρχουν ακόμη δημόσια events για αυτό το weekend.",events:"events",cities:"πόλεις",next:"Επόμενα events",view:"Δες το event"}} as const;
function formatDate(value:string,timezone:string|null,locale:Locale){return new Intl.DateTimeFormat(locale==="el"?"el-GR":"en-GB",{day:"numeric",month:"short",timeZone:timezone||"Europe/Athens"}).format(new Date(value))}
async function loadUpcoming():Promise<Row[]>{const query=new URLSearchParams({select:"id,public_slug,title,event_type,starts_at,ends_at,timezone,city,location_text,country_code",status:"eq.published",order:"starts_at.asc",limit:"100"});try{const response=await fetch(`${SUPABASE_URL}/rest/v1/radar_events?${query}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY},next:{revalidate:120}});if(!response.ok)return[];const rows=await response.json() as Row[];return rows.filter(row=>isEventCurrentlyVisible(row.starts_at,row.ends_at))}catch{return[]}}
export async function RadarHomeSpotlight({locale}:{locale:Locale}){const events=await loadUpcoming();const text=copy[locale];const base=locale==="el"?"/el":"";const weekend=events.filter(event=>event.country_code==="GR"&&matchesDateFilter(event.starts_at,"weekend",event.timezone||"Europe/Athens"));const cities=Array.from(new Set(weekend.map(event=>event.city).filter((city):city is string=>Boolean(city))));const cards=(weekend.length?weekend:events).slice(0,3);return <section className={styles.section} aria-labelledby="weekend-heading"><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}><span aria-hidden="true"/>{text.eyebrow}</p><h2 id="weekend-heading">{text.title}</h2><p className={styles.body}>{text.body}</p><div className={styles.weekendStats}><strong>{weekend.length}</strong><span>{text.events}</span><i>·</i><strong>{cities.length}</strong><span>{text.cities}</span></div>{cities.length?<p className={styles.cityLine}>{cities.slice(0,5).join(" · ")}</p>:null}</div><Link className={styles.cta} href={`${base}/meets?country=GR&date=weekend`}>{text.cta} <span aria-hidden="true">→</span></Link></div>{weekend.length===0?<div className={styles.weekendEmpty}>{text.empty}</div>:null}{cards.length?<div className={styles.grid}>{cards.map(event=><Link className={styles.card} href={`${base}/meets/${event.public_slug}`} key={event.id}><div className={styles.cardTop}><span>{formatDate(event.starts_at,event.timezone,locale)}</span><span>{CATEGORY[event.event_type]??"EVENT"}</span></div><h3>{event.title}</h3><p>{event.city??event.location_text??event.country_code}</p><span className={styles.cardLink}>{text.view} →</span></Link>)}</div>:null}</div></section>}
